### PR TITLE
Working towards MVP-A

### PR DESCRIPTION
**Pull request by jgoodhcg**

### CODE REVIEW

**Comment by jgoodhcg** [comment]
[cycle through days displayed](https://trello.com/c/0iFQeDn0/23-cycle-through-days-displayed)

**Comment by royalaid** [comment]
[bug - straddled task doesn't move](https://trello.com/c/j01SU5F4/30-bug-straddled-task-doesnt-move)

**Comment by royalaid** [comment]
[lower pane](https://trello.com/c/0KwA8Lu2/10-lower-pane)

**Comment by royalaid** [comment]
[lower pane](https://trello.com/c/0KwA8Lu2/10-lower-pane)

**Pull request merged**
